name: flutter_app
description: A new Flutter project.

dependencies:
  http: '>=0.11.3+12'
  flutter:
    sdk: flutter
  flutter_webview_plugin:
#    path: ../
  cupertino_icons: ^0.1.0
  url_launcher: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

